# Build arXiv PDF Text Corpus (PyMuPDF + pypdf)

Notebook này mở rộng pipeline benchmark theo hướng gần thực tế hơn:

- Crawl/tải PDF từ **arXiv** theo **cùng domain**
- Parse mỗi PDF bằng nhiều parser text-based:
  - **PyMuPDF**
  - **pypdf**

- Tạo benchmark:
  - **positive pairs**: cùng tài liệu, khác parser/OCR method
  - **hard negatives**: khác tài liệu nhưng cùng domain
  - **online stream benchmark**

## 0. Cài thư viện cơ bản

Cell này cài các thư viện nhẹ để crawl, parse text-based và render PDF.

In [1]:
%pip -q install requests feedparser pymupdf pypdf tqdm pandas

Note: you may need to restart the kernel to use updated packages.

## 1. Cài Tesseract hệ thống

In [2]:
# Không cần cài Tesseract vì chỉ chạy PyMuPDF và pypdf
# !apt-get update -y
# !apt-get install -y tesseract-ocr poppler-utils

## 2. Import và cấu hình

In [3]:
from pathlib import Path
import re
import os
import json
import time
import math
import hashlib
import random
import requests
import feedparser
import pandas as pd
from tqdm.auto import tqdm
from itertools import combinations

random.seed(42)

BASE_DIR = Path("arxiv_ocr_benchmark_workspace")
PDF_DIR = BASE_DIR / "pdfs"
META_DIR = BASE_DIR / "metadata"
PARSED_DIR = BASE_DIR / "parsed_jsonl"
BENCH_DIR = BASE_DIR / "benchmark"

for d in [PDF_DIR, META_DIR, PARSED_DIR, BENCH_DIR]:
    d.mkdir(parents=True, exist_ok=True)

BASE_DIR

c:\Users\pntha\AppData\Local\Programs\Python\Python312\Lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

WindowsPath('arxiv_ocr_benchmark_workspace')

## 3. arXiv API search

Mặc định nên dùng **một category/domain** để hard negatives khó hơn.

In [4]:
ARXIV_API_URL = "http://export.arxiv.org/api/query"

def search_arxiv(query: str, start: int = 0, max_results: int = 20, sort_by: str = "submittedDate", sort_order: str = "descending"):
    params = {
        "search_query": query,
        "start": start,
        "max_results": max_results,
        "sortBy": sort_by,
        "sortOrder": sort_order,
    }
    r = requests.get(ARXIV_API_URL, params=params, timeout=60)
    r.raise_for_status()
    feed = feedparser.parse(r.text)

    rows = []
    for entry in feed.entries:
        pdf_url = None
        for link in entry.get("links", []):
            if link.get("type") == "application/pdf":
                pdf_url = link.get("href")
                break

        rows.append({
            "id": entry.get("id"),
            "arxiv_id": entry.get("id", "").rstrip("/").split("/")[-1],
            "title": re.sub(r"\s+", " ", entry.get("title", "")).strip(),
            "summary": re.sub(r"\s+", " ", entry.get("summary", "")).strip(),
            "published": entry.get("published"),
            "updated": entry.get("updated"),
            "authors": [a.get("name") for a in entry.get("authors", [])],
            "pdf_url": pdf_url,
            "primary_category": entry.get("arxiv_primary_category", {}).get("term"),
            "categories": [t["term"] for t in entry.get("tags", [])] if entry.get("tags") else [],
        })
    return pd.DataFrame(rows)

In [5]:
QUERIES = [
    "cat:cs.CL AND all:question answering",
    "cat:cs.CL AND all:information extraction",
    "cat:cs.CL AND all:summarization",
    "cat:cs.CL AND all:machine translation",
    "cat:cs.CL AND all:retrieval augmented generation",

    "cat:cs.IR AND all:retrieval",
    "cat:cs.IR AND all:reranking",
    "cat:cs.IR AND all:dense retrieval",
    "cat:cs.IR AND all:document ranking",
    "cat:cs.IR AND all:search",

    "cat:cs.LG AND all:contrastive learning",
    "cat:cs.LG AND all:representation learning",
    "cat:cs.LG AND all:domain adaptation",
    "cat:cs.LG AND all:self supervised learning",

    "cat:cs.AI AND all:knowledge graphs",
    "cat:cs.AI AND all:reasoning",
    "cat:cs.AI AND all:planning",
    "cat:cs.AI AND all:agents",
]
MAX_RESULTS_PER_QUERY = 150

all_meta = []
for query in QUERIES:
    df_q = search_arxiv(query=query, max_results=MAX_RESULTS_PER_QUERY)
    df_q["requested_query"] = query
    all_meta.append(df_q)

df = (
    pd.concat(all_meta, ignore_index=True)
    .drop_duplicates(subset=["arxiv_id"])
    .reset_index(drop=True)
)

print("Số query:", len(QUERIES))
print("Số bài sau khi gộp và bỏ trùng:", len(df))
df[["arxiv_id", "title", "primary_category", "requested_query", "published"]].head(10)

Số query: 18
Số bài sau khi gộp và bỏ trùng: 1579

,arxiv_id,title,primary_category,requested_query,published
0,2604.01212v1,$\texttt{YC-Bench}$: Benchmarking AI Agents fo...,cs.CL,cat:cs.CL AND all:question answering,2026-04-01T17:52:19Z
1,2604.01195v1,ORBIT: Scalable and Verifiable Data Generation...,cs.CL,cat:cs.CL AND all:question answering,2026-04-01T17:42:41Z
2,2604.01193v1,Embarrassingly Simple Self-Distillation Improv...,cs.CL,cat:cs.CL AND all:question answering,2026-04-01T17:39:50Z
3,2604.01181v1,True (VIS) Lies: Analyzing How Generative AI R...,cs.HC,cat:cs.CL AND all:question answering,2026-04-01T17:33:10Z
4,2604.01029v1,Revision or Re-Solving? Decomposing Second-Pas...,cs.SE,cat:cs.CL AND all:question answering,2026-04-01T15:39:40Z
5,2604.00986v1,Do Phone-Use Agents Respect Your Privacy?,cs.CR,cat:cs.CL AND all:question answering,2026-04-01T14:50:50Z
6,2604.00913v1,Benchmarking and Mechanistic Analysis of Visio...,cs.CV,cat:cs.CL AND all:question answering,2026-04-01T13:55:28Z
7,2604.00890v1,Beyond Symbolic Solving: Multi Chain-of-Though...,cs.AI,cat:cs.CL AND all:question answering,2026-04-01T13:37:06Z
8,2604.00778v1,From Early Encoding to Late Suppression: Inter...,cs.CL,cat:cs.CL AND all:question answering,2026-04-01T11:40:12Z
9,2604.00698v1,Learning to Hint for Reinforcement Learning,cs.LG,cat:cs.CL AND all:question answering,2026-04-01T09:58:08Z

In [6]:
meta_csv_path = META_DIR / "arxiv_search_results_multi_query.csv"
meta_jsonl_path = META_DIR / "arxiv_search_results_multi_query.jsonl"


df.to_csv(meta_csv_path, index=False, encoding="utf-8")

with open(meta_jsonl_path, "w", encoding="utf-8") as f:
    for row in df.to_dict(orient="records"):
        f.write(json.dumps(row, ensure_ascii=False) + "\n")

print(meta_csv_path)
print(meta_jsonl_path)

arxiv_ocr_benchmark_workspace\metadata\arxiv_search_results_multi_query.csv
arxiv_ocr_benchmark_workspace\metadata\arxiv_search_results_multi_query.jsonl

In [7]:
len(df)

1579

## 4. Tải PDF

In [8]:
from concurrent.futures import ThreadPoolExecutor, as_completed

def safe_filename(text: str) -> str:
    text = re.sub(r"[^A-Za-z0-9._-]+", "_", text)
    return text[:180]

def download_pdf(row, pdf_dir: Path, sleep_sec: float = 0.5, overwrite: bool = False):
    arxiv_id = row["arxiv_id"]
    pdf_url = row["pdf_url"]

    if not pdf_url:
        return {
            "arxiv_id": arxiv_id,
            "pdf_path": None,
            "ok": False,
            "error": "missing_pdf_url",
        }

    out_path = pdf_dir / f"{safe_filename(arxiv_id)}.pdf"

    if out_path.exists() and not overwrite:
        return {
            "arxiv_id": arxiv_id,
            "pdf_path": str(out_path),
            "ok": True,
            "cached": True,
        }

    r = requests.get(pdf_url, timeout=120)
    r.raise_for_status()
    out_path.write_bytes(r.content)
    time.sleep(sleep_sec)

    return {
        "arxiv_id": arxiv_id,
        "pdf_path": str(out_path),
        "ok": True,
        "cached": False,
    }

def download_pdfs_in_batches(
    df,
    pdf_dir: Path,
    batch_size: int = 50,
    max_workers: int = 8,
    sleep_sec: float = 0.5,
    overwrite: bool = False,
):
    rows = df.to_dict(orient="records")
    results = []

    for start in range(0, len(rows), batch_size):
        batch_rows = rows[start:start + batch_size]

        with ThreadPoolExecutor(max_workers=max_workers) as ex:
            futures = {
                ex.submit(download_pdf, row, pdf_dir, sleep_sec, overwrite): row
                for row in batch_rows
            }

            for fut in tqdm(as_completed(futures), total=len(futures), desc=f"Batch {start//batch_size + 1}"):
                try:
                    results.append(fut.result())
                except Exception as e:
                    row = futures[fut]
                    results.append({
                        "arxiv_id": row.get("arxiv_id"),
                        "pdf_path": None,
                        "ok": False,
                        "error": str(e),
                    })

        time.sleep(2.0)

    return pd.DataFrame(results)

download_df = download_pdfs_in_batches(
    df=df,
    pdf_dir=PDF_DIR,
    batch_size=50,
    max_workers=8,
    sleep_sec=0.5,
    overwrite=False,
)

download_df.head()

Batch 1: 100%|██████████| 50/50 [00:25<00:00,  1.99it/s]
Batch 2: 100%|██████████| 50/50 [00:22<00:00,  2.21it/s]
Batch 3: 100%|██████████| 50/50 [00:19<00:00,  2.51it/s]
Batch 4: 100%|██████████| 50/50 [00:22<00:00,  2.18it/s]
Batch 5: 100%|██████████| 50/50 [00:25<00:00,  1.99it/s]
Batch 6: 100%|██████████| 50/50 [00:17<00:00,  2.93it/s]
Batch 7: 100%|██████████| 50/50 [00:26<00:00,  1.89it/s]
Batch 8: 100%|██████████| 50/50 [00:19<00:00,  2.61it/s]
Batch 9: 100%|██████████| 50/50 [00:21<00:00,  2.30it/s]
Batch 10: 100%|██████████| 50/50 [00:16<00:00,  2.96it/s]
Batch 11: 100%|██████████| 50/50 [00:19<00:00,  2.58it/s]
Batch 12: 100%|██████████| 50/50 [00:17<00:00,  2.87it/s]
Batch 13: 100%|██████████| 50/50 [00:20<00:00,  2.40it/s]
Batch 14: 100%|██████████| 50/50 [00:15<00:00,  3.15it/s]
Batch 15: 100%|██████████| 50/50 [00:20<00:00,  2.48it/s]
Batch 16: 100%|██████████| 50/50 [00:21<00:00,  2.27it/s]
Batch 17: 100%|██████████| 50/50 [00:23<00:00,  2.16it/s]
Batch 18: 100%|██████████| 50/50 [00:21<00:00,  2.37it/s]
Batch 19: 100%|██████████| 50/50 [00:18<00:00,  2.64it/s]
Batch 20: 100%|██████████| 50/50 [00:23<00:00,  2.13it/s]
Batch 21: 100%|██████████| 50/50 [00:19<00:00,  2.57it/s]
Batch 22: 100%|██████████| 50/50 [00:20<00:00,  2.49it/s]
Batch 23: 100%|██████████| 50/50 [00:21<00:00,  2.30it/s]
Batch 24: 100%|██████████| 50/50 [00:24<00:00,  2.07it/s]
Batch 25: 100%|██████████| 50/50 [00:20<00:00,  2.44it/s]
Batch 26: 100%|██████████| 50/50 [00:15<00:00,  3.14it/s]
Batch 27: 100%|██████████| 50/50 [00:20<00:00,  2.44it/s]
Batch 28: 100%|██████████| 50/50 [00:20<00:00,  2.44it/s]
Batch 29: 100%|██████████| 50/50 [00:23<00:00,  2.09it/s]
Batch 30: 100%|██████████| 50/50 [00:25<00:00,  1.99it/s]
Batch 31: 100%|██████████| 50/50 [00:19<00:00,  2.61it/s]
Batch 32: 100%|██████████| 29/29 [00:10<00:00,  2.71it/s]

,arxiv_id,pdf_path,ok,cached,error
0,2604.00890v1,arxiv_ocr_benchmark_workspace\pdfs\2604.00890v...,True,False,NaN
1,2604.00913v1,arxiv_ocr_benchmark_workspace\pdfs\2604.00913v...,True,False,NaN
2,2604.01195v1,arxiv_ocr_benchmark_workspace\pdfs\2604.01195v...,True,False,NaN
3,2604.01212v1,arxiv_ocr_benchmark_workspace\pdfs\2604.01212v...,True,False,NaN
4,2604.01029v1,arxiv_ocr_benchmark_workspace\pdfs\2604.01029v...,True,False,NaN

In [9]:
print("Số file PDF trong thư mục:", len(list(PDF_DIR.glob("*.pdf"))))

Số file PDF trong thư mục: 1578

## 5. Text-based parsers

Ba parser này là baseline nhẹ, nhanh.

In [10]:
import fitz
from pypdf import PdfReader

def extract_with_pymupdf(pdf_path: str):
    doc = fitz.open(pdf_path)
    pages = []
    for i, page in enumerate(doc):
        txt = page.get_text("text")
        pages.append({"page_num": i + 1, "text": txt})
    return {
        "parser": "pymupdf",
        "page_count": len(pages),
        "pages": pages,
        "text": "\n\n".join(p["text"] for p in pages),
    }

def extract_with_pypdf(pdf_path: str):
    reader = PdfReader(pdf_path)
    pages = []
    for i, page in enumerate(reader.pages):
        try:
            txt = page.extract_text() or ""
        except Exception:
            txt = ""
        pages.append({"page_num": i + 1, "text": txt})
    return {
        "parser": "pypdf",
        "page_count": len(pages),
        "pages": pages,
        "text": "\n\n".join(p["text"] for p in pages),
    }

## 10. Chuẩn hóa và đóng gói output

In [11]:
def normalize_text(text: str) -> str:
    if text is None:
        return ""
    text = text.replace("\x00", " ")
    text = re.sub(r"\r\n?", "\n", text)
    text = re.sub(r"[ \t]+", " ", text)
    text = re.sub(r"\n{3,}", "\n\n", text)
    return text.strip()

def sha1_text(text: str) -> str:
    return hashlib.sha1(text.encode("utf-8", errors="ignore")).hexdigest()

def build_record(meta_row: dict, pdf_path: str, parsed: dict):
    text = normalize_text(parsed["text"])
    return {
        "doc_id": meta_row["arxiv_id"],
        "source_pdf": str(pdf_path),
        "parser_name": parsed["parser"],
        "text": text,
        "text_sha1": sha1_text(text),
        "char_count": len(text),
        "page_count": parsed["page_count"],
        "pages": parsed["pages"],
        "metadata": {
            "title": meta_row["title"],
            "summary": meta_row["summary"],
            "published": meta_row["published"],
            "updated": meta_row["updated"],
            "authors": meta_row["authors"],
            "pdf_url": meta_row["pdf_url"],
            "primary_category": meta_row["primary_category"],
            "categories": meta_row["categories"],
            "source": "arxiv",
        }
    }

## 11. Chọn parser nào sẽ chạy thực tế

Mặc định chạy:
- **PyMuPDF**
- **pypdf**

In [13]:
from pathlib import Path

PARSERS = {
    "pymupdf": extract_with_pymupdf,
    "pypdf": extract_with_pypdf,
}

if RUN_TESSERACT:
    PARSERS["tesseract_ocr"] = lambda pdf_path: extract_with_tesseract(
        pdf_path=pdf_path,
        image_dir=IMG_DIR,
        dpi=OCR_DPI,
        max_pages=OCR_MAX_PAGES,
        lang=OCR_LANG,
    )

if RUN_LIGHTON:
    PARSERS["lightonocr_2_1b"] = lambda pdf_path: extract_with_lightonocr(
        pdf_path=pdf_path,
        image_dir=IMG_DIR,
        dpi=OCR_DPI,
        max_pages=OCR_MAX_PAGES,
        batch_size=OCR_MODEL_BATCH_SIZE,
    )

if RUN_QWEN_OCR:
    PARSERS["qwen2_5_vl_7b_ocr"] = lambda pdf_path: extract_with_qwen_ocr(
        pdf_path=pdf_path,
        image_dir=IMG_DIR,
        dpi=OCR_DPI,
        max_pages=OCR_MAX_PAGES,
        batch_size=OCR_MODEL_BATCH_SIZE,
    )

print("Parsers sẽ chạy:", list(PARSERS.keys()))

Parsers sẽ chạy: ['pymupdf', 'pypdf']

## 12. Parse toàn bộ PDF bằng các parser đã chọn

In [14]:
records = []
errors = []

meta_by_id = {row["arxiv_id"]: row for _, row in df.iterrows()}

for pdf_path in tqdm(sorted(PDF_DIR.glob("*.pdf"))):
    arxiv_id = pdf_path.stem
    if arxiv_id not in meta_by_id:
        continue

    meta_row = meta_by_id[arxiv_id]
    for parser_name, parser_fn in PARSERS.items():
        try:
            parsed = parser_fn(str(pdf_path))
            rec = build_record(meta_row, str(pdf_path), parsed)
            records.append(rec)
        except Exception as e:
            errors.append({
                "doc_id": arxiv_id,
                "parser_name": parser_name,
                "pdf_path": str(pdf_path),
                "error": str(e),
            })

print("Số parser outputs:", len(records))
print("Số lỗi parse:", len(errors))

 12%|█▏        | 184/1578 [03:04<34:22,  1.48s/it] Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 32 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 54 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 61 0 (offset 0)
Ignoring wrong pointing object 73 0 (offset 0)
Ignoring wrong pointing object 75 0 (offset 0)
Ignoring wrong pointing object 119 0 (offset 0)
Ignoring wrong pointing object 145 0 (offset 0)
Ignoring wrong pointing object 150 0 (offset 0)
 17%|█▋        | 262/1578 [04:37<33:34,  1.53s/it]  Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 34 0 (offset 0)
Ignoring wrong pointing object 36 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
 17%|█▋        | 266/1578 [04:58<1:50:50,  5.07s/it]Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 20 0 (offset 0)
Ignoring wrong pointing object 22 0 (offset 0)
Ignoring wrong pointing object 24 0 (offset 0)
Ignoring wrong pointing object 26 0 (offset 0)
Ignoring wrong pointing object 32 0 (offset 0)
Ignoring wrong pointing object 34 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 41 0 (offset 0)
Ignoring wrong pointing object 43 0 (offset 0)
 26%|██▌       | 410/1578 [09:43<35:33,  1.83s/it]  Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 20 0 (offset 0)
Ignoring wrong pointing object 49 0 (offset 0)
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 58 0 (offset 0)
Ignoring wrong pointing object 60 0 (offset 0)
Ignoring wrong pointing object 62 0 (offset 0)
Ignoring wrong pointing object 65 0 (offset 0)
Ignoring wrong pointing object 103 0 (offset 0)
 29%|██▉       | 456/1578 [10:24<26:34,  1.42s/it]Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 20 0 (offset 0)
Ignoring wrong pointing object 57 0 (offset 0)
 29%|██▉       | 465/1578 [10:33<16:44,  1.11it/s]Ignoring wrong pointing object 5 0 (offset 0)
Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 26 0 (offset 0)
Ignoring wrong pointing object 28 0 (offset 0)
 30%|██▉       | 473/1578 [10:41<19:53,  1.08s/it]Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 20 0 (offset 0)
Ignoring wrong pointing object 22 0 (offset 0)
Ignoring wrong pointing object 24 0 (offset 0)
Ignoring wrong pointing object 26 0 (offset 0)
Ignoring wrong pointing object 32 0 (offset 0)
Ignoring wrong pointing object 34 0 (offset 0)
Ignoring wrong pointing object 36 0 (offset 0)
Ignoring wrong pointing object 38 0 (offset 0)
Ignoring wrong pointing object 40 0 (offset 0)
Ignoring wrong pointing object 42 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)
Ignoring wrong pointing object 49 0 (offset 0)
Ignoring wrong pointing object 54 0 (offset 0)
Ignoring wrong pointing object 60 0 (offset 0)
 35%|███▌      | 556/1578 [12:58<15:46,  1.08it/s]  Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 66 0 (offset 0)
 41%|████      | 648/1578 [14:52<32:16,  2.08s/it]

MuPDF error: syntax error: unknown keyword: 'minorversion'

 57%|█████▋    | 895/1578 [19:44<20:21,  1.79s/it]  Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 25 0 (offset 0)
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 29 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 41 0 (offset 0)
Ignoring wrong pointing object 43 0 (offset 0)
Ignoring wrong pointing object 55 0 (offset 0)
Ignoring wrong pointing object 62 0 (offset 0)
Ignoring wrong pointing object 94 0 (offset 0)
 59%|█████▊    | 925/1578 [20:08<09:55,  1.10it/s]Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 28 0 (offset 0)
Ignoring wrong pointing object 32 0 (offset 0)
Ignoring wrong pointing object 50 0 (offset 0)
Ignoring wrong pointing object 73 0 (offset 0)
Ignoring wrong pointing object 96 0 (offset 0)
Ignoring wrong pointing object 98 0 (offset 0)
Ignoring wrong pointing object 108 0 (offset 0)
Ignoring wrong pointing object 110 0 (offset 0)
Ignoring wrong pointing object 112 0 (offset 0)
Ignoring wrong pointing object 119 0 (offset 0)
 62%|██████▏   | 976/1578 [20:43<05:12,  1.93it/s]

MuPDF error: format error: cmsOpenProfileFromMem failed

 65%|██████▍   | 1022/1578 [21:19<07:25,  1.25it/s]Ignoring wrong pointing object 45 0 (offset 0)
 70%|███████   | 1105/1578 [23:09<08:08,  1.03s/it]  Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 33 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 38 0 (offset 0)
Ignoring wrong pointing object 53 0 (offset 0)
Ignoring wrong pointing object 55 0 (offset 0)
Ignoring wrong pointing object 60 0 (offset 0)
Ignoring wrong pointing object 62 0 (offset 0)
Ignoring wrong pointing object 64 0 (offset 0)
Ignoring wrong pointing object 70 0 (offset 0)
Ignoring wrong pointing object 93 0 (offset 0)
 75%|███████▍  | 1180/1578 [25:32<08:02,  1.21s/it]  Ignoring wrong pointing object 12 0 (offset 0)
 76%|███████▋  | 1207/1578 [26:24<26:07,  4.22s/it]Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 20 0 (offset 0)
Ignoring wrong pointing object 22 0 (offset 0)
Ignoring wrong pointing object 86 0 (offset 0)
Ignoring wrong pointing object 121 0 (offset 0)
Ignoring wrong pointing object 123 0 (offset 0)
Ignoring wrong pointing object 133 0 (offset 0)
Ignoring wrong pointing object 135 0 (offset 0)
 82%|████████▏ | 1288/1578 [28:22<08:29,  1.76s/it]Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 24 0 (offset 0)
Ignoring wrong pointing object 26 0 (offset 0)
Ignoring wrong pointing object 28 0 (offset 0)
Ignoring wrong pointing object 33 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 40 0 (offset 0)
Ignoring wrong pointing object 46 0 (offset 0)
Ignoring wrong pointing object 51 0 (offset 0)
Ignoring wrong pointing object 56 0 (offset 0)
Ignoring wrong pointing object 71 0 (offset 0)
Ignoring wrong pointing object 76 0 (offset 0)
Ignoring wrong pointing object 78 0 (offset 0)
Ignoring wrong pointing object 143 0 (offset 0)
Ignoring wrong pointing object 146 0 (offset 0)
Ignoring wrong pointing object 177 0 (offset 0)
Ignoring wrong pointing object 178 0 (offset 0)
 85%|████████▍ | 1340/1578 [29:56<05:17,  1.33s/it]Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 20 0 (offset 0)
Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 29 0 (offset 0)
Ignoring wrong pointing object 31 0 (offset 0)
Ignoring wrong pointing object 39 0 (offset 0)
Ignoring wrong pointing object 41 0 (offset 0)
Ignoring wrong pointing object 43 0 (offset 0)
Ignoring wrong pointing object 45 0 (offset 0)
Ignoring wrong pointing object 55 0 (offset 0)
Ignoring wrong pointing object 57 0 (offset 0)
Ignoring wrong pointing object 59 0 (offset 0)
Ignoring wrong pointing object 78 0 (offset 0)
Ignoring wrong pointing object 83 0 (offset 0)
 87%|████████▋ | 1366/1578 [30:27<04:40,  1.32s/it]Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 42 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)
 87%|████████▋ | 1371/1578 [30:31<03:19,  1.04it/s]Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 18 0 (offset 0)
Ignoring wrong pointing object 24 0 (offset 0)
Ignoring wrong pointing object 26 0 (offset 0)
Ignoring wrong pointing object 28 0 (offset 0)
Ignoring wrong pointing object 34 0 (offset 0)
Ignoring wrong pointing object 36 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)
Ignoring wrong pointing object 46 0 (offset 0)
 88%|████████▊ | 1384/1578 [31:03<07:12,  2.23s/it]Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 12 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 20 0 (offset 0)
Ignoring wrong pointing object 31 0 (offset 0)
Ignoring wrong pointing object 33 0 (offset 0)
Ignoring wrong pointing object 35 0 (offset 0)
Ignoring wrong pointing object 37 0 (offset 0)
Ignoring wrong pointing object 40 0 (offset 0)
Ignoring wrong pointing object 44 0 (offset 0)
Ignoring wrong pointing object 47 0 (offset 0)
Ignoring wrong pointing object 55 0 (offset 0)
Ignoring wrong pointing object 79 0 (offset 0)
Ignoring wrong pointing object 103 0 (offset 0)
Ignoring wrong pointing object 149 0 (offset 0)
Ignoring wrong pointing object 176 0 (offset 0)
Ignoring wrong pointing object 230 0 (offset 0)
Ignoring wrong pointing object 245 0 (offset 0)
Ignoring wrong pointing object 271 0 (offset 0)
Ignoring wrong pointing object 272 0 (offset 0)
 99%|█████████▊| 1556/1578 [37:57<00:28,  1.30s/it]Ignoring wrong pointing object 6 0 (offset 0)
Ignoring wrong pointing object 8 0 (offset 0)
Ignoring wrong pointing object 10 0 (offset 0)
Ignoring wrong pointing object 14 0 (offset 0)
Ignoring wrong pointing object 16 0 (offset 0)
Ignoring wrong pointing object 22 0 (offset 0)
Ignoring wrong pointing object 24 0 (offset 0)
Ignoring wrong pointing object 73 0 (offset 0)
Ignoring wrong pointing object 75 0 (offset 0)
Ignoring wrong pointing object 77 0 (offset 0)
Ignoring wrong pointing object 85 0 (offset 0)
Ignoring wrong pointing object 87 0 (offset 0)
Ignoring wrong pointing object 89 0 (offset 0)
Ignoring wrong pointing object 115 0 (offset 0)
Ignoring wrong pointing object 117 0 (offset 0)
 99%|█████████▉| 1565/1578 [38:11<00:24,  1.86s/it]Ignoring wrong pointing object 7 0 (offset 0)
Ignoring wrong pointing object 9 0 (offset 0)
Ignoring wrong pointing object 11 0 (offset 0)
Ignoring wrong pointing object 13 0 (offset 0)
Ignoring wrong pointing object 15 0 (offset 0)
Ignoring wrong pointing object 17 0 (offset 0)
Ignoring wrong pointing object 19 0 (offset 0)
Ignoring wrong pointing object 21 0 (offset 0)
Ignoring wrong pointing object 23 0 (offset 0)
Ignoring wrong pointing object 25 0 (offset 0)
Ignoring wrong pointing object 27 0 (offset 0)
Ignoring wrong pointing object 29 0 (offset 0)
Ignoring wrong pointing object 31 0 (offset 0)
Ignoring wrong pointing object 34 0 (offset 0)
Ignoring wrong pointing object 36 0 (offset 0)
Ignoring wrong pointing object 38 0 (offset 0)
Ignoring wrong pointing object 40 0 (offset 0)
Ignoring wrong pointing object 42 0 (offset 0)
Ignoring wrong pointing object 55 0 (offset 0)
Ignoring wrong pointing object 57 0 (offset 0)
100%|██████████| 1578/1578 [38:59<00:00,  1.48s/it]

Số parser outputs: 3156
Số lỗi parse: 0

In [15]:
parsed_df = pd.DataFrame([
    {
        "doc_id": r["doc_id"],
        "parser_name": r["parser_name"],
        "char_count": r["char_count"],
        "page_count": r["page_count"],
        "text_sha1": r["text_sha1"],
        "primary_category": r["metadata"]["primary_category"],
        "title": r["metadata"]["title"],
    }
    for r in records
])

parsed_df.head(20)

,doc_id,parser_name,char_count,page_count,text_sha1,primary_category,title
0,2507.21563v3,pymupdf,66139,15,99af3a19398330797fa6a712f4ccbe032bbadb11,cs.IR,VoteGCL: Enhancing Graph-based Recommendations...
1,2507.21563v3,pypdf,70498,15,9b914e7416830bcb4a2345dad3ad46e569b889d9,cs.IR,VoteGCL: Enhancing Graph-based Recommendations...
2,2508.01514v1,pymupdf,39835,7,802c84aa6a58e082118c6ff9c995153ddfd42490,cs.IR,End-to-End Personalization: Unifying Recommend...
3,2508.01514v1,pypdf,39857,7,8a5f290830d268aa011a0dd601e80634ccc842c5,cs.IR,End-to-End Personalization: Unifying Recommend...
4,2508.05512v1,pymupdf,31570,6,c78e1930a7b0d1c1a308c4ed041c5c0c9afb0983,cs.IR,RankArena: A Unified Platform for Evaluating R...
5,2508.05512v1,pypdf,31523,6,2ea9ee4d8816d9d4dc46e4f5d6dd4a600ee3753e,cs.IR,RankArena: A Unified Platform for Evaluating R...
6,2508.05664v1,pymupdf,14057,6,e7104b40189016cfe2c4ea4ce5580180778b3676,cs.IR,Enhancing Retrieval-Augmented Generation for E...
7,2508.05664v1,pypdf,13993,6,6b266312d01e89a0a71ca7633f92b0796364f98e,cs.IR,Enhancing Retrieval-Augmented Generation for E...
8,2508.07050v2,pymupdf,97162,21,f3914803ed91bc01f9c7b9a28607cf72ff79d489,cs.IR,ReasonRank: Empowering Passage Ranking with St...
9,2508.07050v2,pypdf,97256,21,c3f0f975e9d0a414d0c528a6c367b026ecbab069,cs.IR,ReasonRank: Empowering Passage Ranking with St...
10,2508.07995v4,pymupdf,52286,15,b20f4185c9d8c8469c8185d01f7a06733f5a509e,cs.IR,DIVER: A Multi-Stage Approach for Reasoning-in...
11,2508.07995v4,pypdf,52083,15,1c6ad96eac449b1ef7fe5abb7b6bc6e7f4198d50,cs.IR,DIVER: A Multi-Stage Approach for Reasoning-in...
12,2508.10068v2,pymupdf,78984,19,5de5797d149dbdea96a2280990d912dab1098113,cs.SE,SaraCoder: Orchestrating Semantic and Structur...
13,2508.10068v2,pypdf,78157,19,fe827512237a38a052b4ee8b343b96af029fdc88,cs.SE,SaraCoder: Orchestrating Semantic and Structur...
14,2508.11670v1,pymupdf,35739,10,c9e38e5da50dcfdea49a3e70d9cb377d97b6e39d,cs.IR,RRRA: Resampling and Reranking through a Retri...
15,2508.11670v1,pypdf,35765,10,e8f8b86dcbb9f6da0cb0f89104e1d17adcdc806d,cs.IR,RRRA: Resampling and Reranking through a Retri...
16,2508.13517v1,pymupdf,51008,8,860943a7b3f08b0ed7c497db9a6e7064ad4cb925,cs.IR,Heterogeneous Influence Maximization in User R...
17,2508.13517v1,pypdf,50562,8,ea9b5f0704807131486786b843ae6ff1a86acebe,cs.IR,Heterogeneous Influence Maximization in User R...
18,2508.13889v2,pymupdf,48995,18,cb38ac945b2b082808920c604faedd040edc085a,cs.IR,Improving Conversational Recommendation with C...
19,2508.13889v2,pypdf,48750,18,1c3d969cc30f23d6b4b9c6dd04f59651de2a20cc,cs.IR,Improving Conversational Recommendation with C...

## 13. Xuất JSONL parser outputs

In [17]:
all_jsonl_path = PARSED_DIR / "arxiv_multi_parser_ocr_all.jsonl"
with open(all_jsonl_path, "w", encoding="utf-8", errors='replace') as f:
    for r in records:
        f.write(json.dumps(r, ensure_ascii=False) + "\n")
print(all_jsonl_path)

for parser_name in sorted(set(r["parser_name"] for r in records)):
    parser_path = PARSED_DIR / f"{parser_name}.jsonl"
    with open(parser_path, "w", encoding="utf-8", errors='replace') as f:
        for r in records:
            if r["parser_name"] == parser_name:
                f.write(json.dumps(r, ensure_ascii=False) + "\n")
    print(parser_path)

arxiv_ocr_benchmark_workspace\parsed_jsonl\arxiv_multi_parser_ocr_all.jsonl
arxiv_ocr_benchmark_workspace\parsed_jsonl\pymupdf.jsonl
arxiv_ocr_benchmark_workspace\parsed_jsonl\pypdf.jsonl

## 14. Kiểm tra cùng document có ra nhiều version text khác nhau không

In [18]:
summary = (
    parsed_df.groupby("doc_id")
    .agg(
        n_parsers=("parser_name", "nunique"),
        n_unique_texts=("text_sha1", "nunique"),
        min_chars=("char_count", "min"),
        max_chars=("char_count", "max"),
    )
    .reset_index()
    .sort_values(["n_unique_texts", "max_chars"], ascending=[False, False])
)

summary.head(20)

            doc_id  n_parsers  n_unique_texts  min_chars  max_chars
508   2603.20179v2          2               2     924182     928306
751   2603.25100v1          2               2     681628     682449
545   2603.21152v3          2               2     437319     509082
796   2603.25681v1          2               2     469528     471820
254   2602.20507v1          2               2     421194     421568
741   2603.24955v1          2               2     347119     348733
805   2603.25862v1          2               2     329282     329897
1394  2604.00324v1          2               2     317547     318103
738   2603.24917v1          2               2     313538     316984
127   2601.14004v3          2               2     310624     312266
1014  2603.27771v1          2               2     266308     272291
707   2603.24318v1          2               2     270893     271996
1577  2604.01221v1          2               2     252085     264063
150   2601.20659v1          2               2     261219     263519
186   2602.06960v2          2               2     175703     252454
590   2603.22327v1          2               2     237169     238011
1234  2603.29353v1          2               2     231487     232369
950   2603.27303v1          2               2     228883     229212
900   2603.26930v1          2               2     224747     229204
1196  2603.29088v1          2               2     226041     227733

## 15. Tạo positive pairs

Positive:
- cùng `doc_id`
- khác `parser_name`

Điều này cho phép positive được sinh cả từ:
- parser text-based khác nhau
- OCR vs non-OCR
- model OCR khác nhau

In [19]:
mini_records = [
    {
        "doc_id": r["doc_id"],
        "parser_name": r["parser_name"],
        "text_sha1": r["text_sha1"],
        "char_count": r["char_count"],
        "primary_category": r["metadata"]["primary_category"],
        "title": r["metadata"]["title"],
    }
    for r in records
]

by_doc = {}
for r in mini_records:
    by_doc.setdefault(r["doc_id"], []).append(r)

positive_pairs = []
for doc_id, items in by_doc.items():
    for a, b in combinations(items, 2):
        positive_pairs.append({
            "left_doc_id": a["doc_id"],
            "left_parser": a["parser_name"],
            "right_doc_id": b["doc_id"],
            "right_parser": b["parser_name"],
            "left_category": a["primary_category"],
            "right_category": b["primary_category"],
            "label": 1,
            "pair_type": "same_doc_diff_parser",
        })

positive_pairs_df = pd.DataFrame(positive_pairs)
print("Số positive pairs:", len(positive_pairs_df))
positive_pairs_df.head(20)

Số positive pairs: 1578

,left_doc_id,left_parser,right_doc_id,right_parser,left_category,right_category,label,pair_type
0,2507.21563v3,pymupdf,2507.21563v3,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
1,2508.01514v1,pymupdf,2508.01514v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
2,2508.05512v1,pymupdf,2508.05512v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
3,2508.05664v1,pymupdf,2508.05664v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
4,2508.07050v2,pymupdf,2508.07050v2,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
5,2508.07995v4,pymupdf,2508.07995v4,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
6,2508.10068v2,pymupdf,2508.10068v2,pypdf,cs.SE,cs.SE,1,same_doc_diff_parser
7,2508.11670v1,pymupdf,2508.11670v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
8,2508.13517v1,pymupdf,2508.13517v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
9,2508.13889v2,pymupdf,2508.13889v2,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
10,2508.13930v1,pymupdf,2508.13930v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
11,2508.14420v1,pymupdf,2508.14420v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
12,2508.16757v1,pymupdf,2508.16757v1,pypdf,cs.CL,cs.CL,1,same_doc_diff_parser
13,2508.16998v1,pymupdf,2508.16998v1,pypdf,cs.CL,cs.CL,1,same_doc_diff_parser
14,2508.18132v1,pymupdf,2508.18132v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
15,2508.20408v1,pymupdf,2508.20408v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
16,2508.21085v1,pymupdf,2508.21085v1,pypdf,cs.CL,cs.CL,1,same_doc_diff_parser
17,2509.00520v1,pymupdf,2509.00520v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
18,2509.02558v1,pymupdf,2509.02558v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser
19,2509.03696v1,pymupdf,2509.03696v1,pypdf,cs.IR,cs.IR,1,same_doc_diff_parser

## 16. Tạo hard negative pairs cùng domain

Hard negative:
- khác `doc_id`
- cùng `primary_category`
- mặc định lấy từ **cùng parser** để benchmark chặt hơn

In [20]:
def build_hard_negatives(records, negatives_per_doc=4, parser_name="pymupdf"):
    pool = [r for r in records if r["parser_name"] == parser_name]
    by_cat = {}
    for r in pool:
        by_cat.setdefault(r["primary_category"], []).append(r)

    negatives = []
    seen = set()

    for cat, items in by_cat.items():
        for a in items:
            candidates = [x for x in items if x["doc_id"] != a["doc_id"]]
            random.shuffle(candidates)
            picked = 0
            for b in candidates:
                key = tuple(sorted([(a["doc_id"], a["parser_name"]), (b["doc_id"], b["parser_name"])]))
                if key in seen:
                    continue
                seen.add(key)
                negatives.append({
                    "left_doc_id": a["doc_id"],
                    "left_parser": a["parser_name"],
                    "right_doc_id": b["doc_id"],
                    "right_parser": b["parser_name"],
                    "left_category": a["primary_category"],
                    "right_category": b["primary_category"],
                    "label": 0,
                    "pair_type": "same_domain_hard_negative",
                })
                picked += 1
                if picked >= negatives_per_doc:
                    break
    return pd.DataFrame(negatives)

NEGATIVE_PARSER = "pymupdf"  # có thể đổi sang "tesseract_ocr" hoặc parser khác
hard_negative_df = build_hard_negatives(mini_records, negatives_per_doc=4, parser_name=NEGATIVE_PARSER)
print("Số hard negative pairs:", len(hard_negative_df))
hard_negative_df.head(20)

Số hard negative pairs: 6080

,left_doc_id,left_parser,right_doc_id,right_parser,left_category,right_category,label,pair_type
0,2507.21563v3,pymupdf,2603.22344v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
1,2507.21563v3,pymupdf,2602.05334v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
2,2507.21563v3,pymupdf,2603.22340v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
3,2507.21563v3,pymupdf,2603.20338v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
4,2508.01514v1,pymupdf,2602.12510v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
5,2508.01514v1,pymupdf,2603.13301v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
6,2508.01514v1,pymupdf,2603.22335v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
7,2508.01514v1,pymupdf,2603.07179v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
8,2508.05512v1,pymupdf,2603.14170v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
9,2508.05512v1,pymupdf,2602.16964v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
10,2508.05512v1,pymupdf,2602.22220v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
11,2508.05512v1,pymupdf,2603.19693v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
12,2508.05664v1,pymupdf,2604.00803v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
13,2508.05664v1,pymupdf,2508.20408v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
14,2508.05664v1,pymupdf,2603.13537v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
15,2508.05664v1,pymupdf,2602.12510v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
16,2508.07050v2,pymupdf,2603.00638v2,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
17,2508.07050v2,pymupdf,2603.22779v2,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
18,2508.07050v2,pymupdf,2603.26807v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative
19,2508.07050v2,pymupdf,2602.23949v1,pymupdf,cs.IR,cs.IR,0,same_domain_hard_negative

## 17. Ghép pair benchmark và xuất file

In [21]:
pair_benchmark_df = pd.concat(
    [positive_pairs_df, hard_negative_df],
    ignore_index=True
).sample(frac=1.0, random_state=42).reset_index(drop=True)

pair_csv = BENCH_DIR / "same_domain_pair_benchmark_with_ocr.csv"
pair_jsonl = BENCH_DIR / "same_domain_pair_benchmark_with_ocr.jsonl"

pair_benchmark_df.to_csv(pair_csv, index=False, encoding="utf-8")
with open(pair_jsonl, "w", encoding="utf-8") as f:
    for row in pair_benchmark_df.to_dict(orient="records"):
        f.write(json.dumps(row, ensure_ascii=False) + "\n")

print(pair_benchmark_df["label"].value_counts(dropna=False))
print(pair_csv)
print(pair_jsonl)

label
0    6080
1    1578
Name: count, dtype: int64
arxiv_ocr_benchmark_workspace\benchmark\same_domain_pair_benchmark_with_ocr.csv
arxiv_ocr_benchmark_workspace\benchmark\same_domain_pair_benchmark_with_ocr.jsonl

## 18. Online stream benchmark

Logic online:
- lần đầu một `doc_id` xuất hiện -> label 0
- các lần sau của cùng `doc_id` -> label 1

In [22]:
stream_df = pd.DataFrame(mini_records).sample(frac=1.0, random_state=42).reset_index(drop=True)

seen = set()
labels = []
for _, row in stream_df.iterrows():
    is_dup = 1 if row["doc_id"] in seen else 0
    labels.append(is_dup)
    seen.add(row["doc_id"])

stream_df["label"] = labels
stream_df["stream_type"] = "online_same_domain_stream"

stream_csv = BENCH_DIR / "same_domain_stream_benchmark_with_ocr.csv"
stream_jsonl = BENCH_DIR / "same_domain_stream_benchmark_with_ocr.jsonl"

stream_df.to_csv(stream_csv, index=False, encoding="utf-8")
with open(stream_jsonl, "w", encoding="utf-8") as f:
    for row in stream_df.to_dict(orient="records"):
        f.write(json.dumps(row, ensure_ascii=False) + "\n")

print(stream_csv)
print(stream_jsonl)
stream_df.head(20)

arxiv_ocr_benchmark_workspace\benchmark\same_domain_stream_benchmark_with_ocr.csv
arxiv_ocr_benchmark_workspace\benchmark\same_domain_stream_benchmark_with_ocr.jsonl

,doc_id,parser_name,text_sha1,char_count,primary_category,title,label,stream_type
0,2604.00977v1,pypdf,5bd3ecacae1e2f004359ae6027a87486a1d24035,49999,cs.LG,Flow-based Policy With Distributional Reinforc...,0,online_same_domain_stream
1,2604.00112v1,pypdf,097928da185b0933c0214d4c4ffe344bea6dc5b1,42736,cs.CR,Efficient Software Vulnerability Detection Usi...,0,online_same_domain_stream
2,2604.00731v1,pypdf,198ded00ddee3132b243047f0e907f90b293a872,42490,cs.IR,STCALIR: Semi-Synthetic Test Collection for Al...,0,online_same_domain_stream
3,2604.00316v1,pypdf,e577423b954a505807374c97c82c3dda06b4b597,70908,stat.ML,Breaking Data Symmetry is Needed For Generaliz...,0,online_same_domain_stream
4,2511.16528v1,pypdf,be65a528f27f46d4e4c978335fe7e10c04262165,34160,cs.CL,TurkColBERT: A Benchmark of Dense and Late-Int...,0,online_same_domain_stream
5,2604.01073v1,pypdf,ab1fa704894564fc3909f71c7891684c9a8cdfa3,35180,cs.CL,Narrative Fingerprints: Multi-Scale Author Ide...,0,online_same_domain_stream
6,2603.29665v1,pypdf,ccb2db7a2e4dbaf9e72f18fded1753bfdb89e255,43747,cs.CL,Near-Miss: Latent Policy Failure Detection in ...,0,online_same_domain_stream
7,2603.29068v2,pymupdf,a005798153ccba81f774f09998ad6c9ab7cf2dc6,46757,cs.LG,ARCS: Autoregressive Circuit Synthesis with To...,0,online_same_domain_stream
8,2604.00754v1,pymupdf,fb2bfe75470d3a589317354a966dedf3c00e543b,47504,cs.CL,Stochastic Attention: Connectome-Inspired Rand...,0,online_same_domain_stream
9,2603.24318v1,pymupdf,01ceeab6e2d5c3babfa595576fa21eb27a065d4e,271996,cs.RO,Toward Generalist Neural Motion Planners for R...,0,online_same_domain_stream
10,2603.24125v1,pypdf,acb1b942d0ccf9cce84f9a177e03f36835ff26d3,65398,cs.CL,Alignment Reduces Expressed but Not Encoded Ge...,0,online_same_domain_stream
11,2603.25531v1,pymupdf,7a388c49319953054754de40b78805b84f20eb92,78530,cs.FL,Synchronous Signal Temporal Logic for Decidabl...,0,online_same_domain_stream
12,2603.01590v1,pymupdf,b1237cfc8dfb61bd8ec3b67bc14b00209d384817,32463,cs.IR,IDProxy: Cold-Start CTR Prediction for Ads and...,0,online_same_domain_stream
13,2602.16136v1,pypdf,cb6e4c38a3beb3c4dd182028b80dfbb813aabddb,25008,cs.IR,Retrieval Collapses When AI Pollutes the Web,0,online_same_domain_stream
14,2601.05200v3,pymupdf,31af728313779b92118e45cae7754480ae167ae6,49313,cs.IR,Multivector Reranking in the Era of Strong Fir...,0,online_same_domain_stream
15,2603.26246v1,pymupdf,64862d09dc8737cafbc3dcfa9f6feabefb0158aa,42987,cs.CL,Distilling Conversations: Abstract Compression...,0,online_same_domain_stream
16,2604.00865v1,pypdf,6ac16c52e2f9e0fb5cbbd71f8e46b6e6b0a2b1a9,61931,cs.IR,Doctor-RAG: Failure-Aware Repair for Agentic R...,0,online_same_domain_stream
17,2602.23964v1,pypdf,8b922f6cd552b0a72e65036f85b2a3f7ecb8b132,27145,cs.IR,RAD-DPO: Robust Adaptive Denoising Direct Pref...,0,online_same_domain_stream
18,2603.29824v1,pypdf,45f78c0d1f70f32fd2dd3ab184e0a553c5c2d93a,62497,cs.LG,Curvature-Guided LoRA: Steering in the pretrai...,0,online_same_domain_stream
19,2603.28963v1,pypdf,3cf0ad6bbdf89f2df506662e8aa87ced9c80bf94,75544,cs.RO,AutoWorld: Scaling Multi-Agent Traffic Simulat...,0,online_same_domain_stream

## 19. Gợi ý dùng thực tế

Thiết lập hợp lý để bắt đầu:

- **Laptop / CPU**:
  - PyMuPDF
  - pypdf
  - pdfplumber
  - Tesseract OCR

- **1 GPU khá**:
  - thêm **LightOnOCR-2-1B**

- **GPU mạnh hơn**:
  - thêm **Qwen2.5-VL-7B-Instruct**

Nếu mục tiêu là benchmark giống paper hơn, bạn có thể dùng:
- parser nhẹ + OCR cổ điển + OCR model
để tạo nhiều version text của cùng PDF.